apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Our base Manifests
resources:
- ../../resources/workload/deployment
- ../../resources/network/service

# These components are for the Deploymnent and Service neither changes per environment.
# Components are shared across each environment. There are no patches for the service and deployment here.
# Because the are the saem for evey environemnt each env will pull the patch from the components (DRY) 
components:
  - ../../components/grafana

# The name suffix will be appended the name of the resources (bases). 
# In this example case our resource names are simply called `base`. 
# So our service and deployment names will end up being:
#  - 'base' + '-guest-book'
# This file as well as the ingress file will need to be aware of this name.
nameSuffix: -grafana

images:
- name: UNDEFINED
  newName: grafana/grafana
  newTag: "latest"

# Annotation Transformer - used to determine where to put annotations
transformers:
- ./transformers.yaml

# The common label used for labels and Selectors.
commonLabels:
  app.kubernetes.io/name: base-grafana

replicas:
- name: base-grafana
  count: 1 

configMapGenerator:
  - name: otel-grafana-config
    options:
      disableNameSuffixHash: true
      labels:
        app: base-grafana
    files:
      - otel-grafana-config.yaml=otel-grafana-config.yaml
    
