apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-zipkin-observability
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: observe
    name: in-cluster
  project: root-project-observability
  source:
    path: overlays/zipkin
    repoURL: https://github.com/jdellostritto/k8s-platform-observe-octo
    targetRevision: HEAD
    