---
- op: replace
  path: /spec/template/spec/containers/0/name
  value: base-tempo
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - name: grpc # OTLP gRPC receiver
      containerPort: 4317
    - name: grafana # Prometheus exporter metrics
      containerPort: 3200
- op: add
  path: /spec/template/spec/containers/0/args
  value: ["-config.file=/etc/otel-tempo-config.yaml"]
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: "Always"
- op: add
  path: /spec/template/spec/volumes
  value: 
    - name: otel-tempo-config-vol
      configMap:
        name: otel-tempo-config
        items:
        - key: otel-tempo-config.yaml
          path: otel-tempo-config.yaml
    - name: tmp-tempo
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: otel-tempo-config-vol
      mountPath: /etc
    - name: tmp-tempo
      mountPath: /tmp/tempo
#- op: remove
#  path: /spec/template/spec/securityContext
#- op: remove
#  path: /spec/template/spec/automountServiceAccountToken
#- op: remove
#  path: /spec/template/spec/containers/0/securityContext
- op: remove
  path: /spec/template/spec/containers/0/resources
