---
- op: replace
  path: /spec/ports
  value:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: grafana
      port: 3200
      targetPort: 3200
- op: add
  path: /spec/type
  value: LoadBalancer