apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: notImportantHere
annotations:
  vgs.com/team: platform
  vgs.com/environment: development
  vgs.com/customer: all
  vgs.com/department: R&D
  vgs.com/criticality: low
  vgs.com/data-sensitivity: low
fieldSpecs:
- kind: Deployment
  path: metadata/annotations
  create: true
- kind: Service
  path: metadata/annotations
  create: true