---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base
  namespace: UNDEFINED
spec:
  ingressClassName: UNDEFINED
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: UNDEFINED
            port:
              number: 80

