apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: ./patch/deployment.yaml
  target:
    kind: Deployment
    name: base
- path: ./patch/service.yaml
  target:
    kind: Service
    name: base
- path: ./patch/persistentVolume.yaml
  target:
    kind: PersistentVolume
    name: base