---
- op: replace
  path: /spec/template/spec/containers/0/name
  value: base-prometheus
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - name: http 
      containerPort: 9090
- op: add
  path: /spec/template/spec/containers/0/args
  value: ["--config.file=/etc/prometheus/otel-prometheus-config.yaml",
      "--enable-feature=exemplar-storage",
      "--web.enable-remote-write-receiver"]
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: "Always"
- op: add
  path: /spec/template/spec/volumes
  value: 
    - name: otel-prometheus-config-vol
      configMap:
        name: otel-prometheus-config
        items:
        - key: otel-prometheus-config.yaml
          path: otel-prometheus-config.yaml
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: otel-prometheus-config-vol
      mountPath: /etc/prometheus
- op: remove
  path: /spec/template/spec/securityContext
- op: remove
  path: /spec/template/spec/automountServiceAccountToken
- op: remove
  path: /spec/template/spec/containers/0/securityContext
- op: remove
  path: /spec/template/spec/containers/0/resources
